// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: liftedinit/billing/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LeaseState defines the state of a lease.
type LeaseState int32

const (
	// LEASE_STATE_UNSPECIFIED is the default value.
	LEASE_STATE_UNSPECIFIED LeaseState = 0
	// LEASE_STATE_ACTIVE indicates the lease is active and accruing charges.
	LEASE_STATE_ACTIVE LeaseState = 1
	// LEASE_STATE_INACTIVE indicates the lease has been closed.
	LEASE_STATE_INACTIVE LeaseState = 2
)

var LeaseState_name = map[int32]string{
	0: "LEASE_STATE_UNSPECIFIED",
	1: "LEASE_STATE_ACTIVE",
	2: "LEASE_STATE_INACTIVE",
}

var LeaseState_value = map[string]int32{
	"LEASE_STATE_UNSPECIFIED": 0,
	"LEASE_STATE_ACTIVE":      1,
	"LEASE_STATE_INACTIVE":    2,
}

func (x LeaseState) String() string {
	return proto.EnumName(LeaseState_name, int32(x))
}

func (LeaseState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{0}
}

// Params defines the parameters for the billing module.
type Params struct {
	// max_leases_per_tenant is the maximum number of active leases a tenant can have.
	// Must be greater than zero.
	MaxLeasesPerTenant uint64 `protobuf:"varint,3,opt,name=max_leases_per_tenant,json=maxLeasesPerTenant,proto3" json:"max_leases_per_tenant,omitempty,string"`
	// allowed_list is the list of addresses allowed to create leases on behalf of tenants
	// in addition to the module authority.
	AllowedList []string `protobuf:"bytes,4,rep,name=allowed_list,json=allowedList,proto3" json:"allowed_list,omitempty"`
	// max_items_per_lease is the maximum number of items (SKUs) allowed in a single lease.
	// Must be greater than zero. Prevents excessive gas consumption from large leases.
	MaxItemsPerLease uint64 `protobuf:"varint,5,opt,name=max_items_per_lease,json=maxItemsPerLease,proto3" json:"max_items_per_lease,omitempty,string"`
	// min_lease_duration is the minimum duration (in seconds) that a tenant's credit balance
	// must be able to cover when creating a lease. This prevents tenants from creating leases
	// that would immediately exhaust their credit. Default is 3600 (1 hour).
	MinLeaseDuration uint64 `protobuf:"varint,6,opt,name=min_lease_duration,json=minLeaseDuration,proto3" json:"min_lease_duration,omitempty,string"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxLeasesPerTenant() uint64 {
	if m != nil {
		return m.MaxLeasesPerTenant
	}
	return 0
}

func (m *Params) GetAllowedList() []string {
	if m != nil {
		return m.AllowedList
	}
	return nil
}

func (m *Params) GetMaxItemsPerLease() uint64 {
	if m != nil {
		return m.MaxItemsPerLease
	}
	return 0
}

func (m *Params) GetMinLeaseDuration() uint64 {
	if m != nil {
		return m.MinLeaseDuration
	}
	return 0
}

// LeaseItem represents a single SKU item within a lease.
type LeaseItem struct {
	// sku_id is the ID of the SKU being leased.
	SkuId uint64 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty,string"`
	// quantity is the number of instances of this SKU.
	Quantity uint64 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty,string"`
	// locked_price is the price per unit locked at lease creation (per second).
	// The denom comes from the SKU's base_price at lease creation time.
	LockedPrice types.Coin `protobuf:"bytes,3,opt,name=locked_price,json=lockedPrice,proto3" json:"locked_price"`
}

func (m *LeaseItem) Reset()         { *m = LeaseItem{} }
func (m *LeaseItem) String() string { return proto.CompactTextString(m) }
func (*LeaseItem) ProtoMessage()    {}
func (*LeaseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{1}
}
func (m *LeaseItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LeaseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LeaseItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LeaseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseItem.Merge(m, src)
}
func (m *LeaseItem) XXX_Size() int {
	return m.Size()
}
func (m *LeaseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseItem.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseItem proto.InternalMessageInfo

func (m *LeaseItem) GetSkuId() uint64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *LeaseItem) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *LeaseItem) GetLockedPrice() types.Coin {
	if m != nil {
		return m.LockedPrice
	}
	return types.Coin{}
}

// Lease represents a billing lease between a tenant and provider.
type Lease struct {
	// id is the unique identifier of the lease.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	// tenant is the address of the tenant who owns this lease.
	Tenant string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// provider_id is the provider ID (denormalized from SKUs for efficient querying).
	ProviderId uint64 `protobuf:"varint,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty,string"`
	// items is the list of SKU items in this lease.
	Items []LeaseItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items"`
	// state is the current state of the lease.
	State LeaseState `protobuf:"varint,5,opt,name=state,proto3,enum=liftedinit.billing.v1.LeaseState" json:"state,omitempty"`
	// created_at is the timestamp when the lease was created.
	CreatedAt time.Time `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// closed_at is the timestamp when the lease was closed (if inactive).
	ClosedAt *time.Time `protobuf:"bytes,7,opt,name=closed_at,json=closedAt,proto3,stdtime" json:"closed_at,omitempty"`
	// last_settled_at is the timestamp of the last settlement/withdrawal.
	LastSettledAt time.Time `protobuf:"bytes,8,opt,name=last_settled_at,json=lastSettledAt,proto3,stdtime" json:"last_settled_at"`
}

func (m *Lease) Reset()         { *m = Lease{} }
func (m *Lease) String() string { return proto.CompactTextString(m) }
func (*Lease) ProtoMessage()    {}
func (*Lease) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{2}
}
func (m *Lease) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Lease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Lease.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Lease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lease.Merge(m, src)
}
func (m *Lease) XXX_Size() int {
	return m.Size()
}
func (m *Lease) XXX_DiscardUnknown() {
	xxx_messageInfo_Lease.DiscardUnknown(m)
}

var xxx_messageInfo_Lease proto.InternalMessageInfo

func (m *Lease) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Lease) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Lease) GetProviderId() uint64 {
	if m != nil {
		return m.ProviderId
	}
	return 0
}

func (m *Lease) GetItems() []LeaseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Lease) GetState() LeaseState {
	if m != nil {
		return m.State
	}
	return LEASE_STATE_UNSPECIFIED
}

func (m *Lease) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *Lease) GetClosedAt() *time.Time {
	if m != nil {
		return m.ClosedAt
	}
	return nil
}

func (m *Lease) GetLastSettledAt() time.Time {
	if m != nil {
		return m.LastSettledAt
	}
	return time.Time{}
}

// CreditAccount represents a tenant's credit account.
// The actual balance is tracked by the bank module at the credit_address.
type CreditAccount struct {
	// tenant is the address of the tenant who owns this credit account.
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// credit_address is the derived address where credit funds are held.
	CreditAddress string `protobuf:"bytes,2,opt,name=credit_address,json=creditAddress,proto3" json:"credit_address,omitempty"`
	// active_lease_count tracks the number of active leases for O(1) count queries.
	ActiveLeaseCount uint64 `protobuf:"varint,3,opt,name=active_lease_count,json=activeLeaseCount,proto3" json:"active_lease_count,omitempty,string"`
}

func (m *CreditAccount) Reset()         { *m = CreditAccount{} }
func (m *CreditAccount) String() string { return proto.CompactTextString(m) }
func (*CreditAccount) ProtoMessage()    {}
func (*CreditAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{3}
}
func (m *CreditAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreditAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreditAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreditAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditAccount.Merge(m, src)
}
func (m *CreditAccount) XXX_Size() int {
	return m.Size()
}
func (m *CreditAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CreditAccount proto.InternalMessageInfo

func (m *CreditAccount) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *CreditAccount) GetCreditAddress() string {
	if m != nil {
		return m.CreditAddress
	}
	return ""
}

func (m *CreditAccount) GetActiveLeaseCount() uint64 {
	if m != nil {
		return m.ActiveLeaseCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("liftedinit.billing.v1.LeaseState", LeaseState_name, LeaseState_value)
	proto.RegisterType((*Params)(nil), "liftedinit.billing.v1.Params")
	proto.RegisterType((*LeaseItem)(nil), "liftedinit.billing.v1.LeaseItem")
	proto.RegisterType((*Lease)(nil), "liftedinit.billing.v1.Lease")
	proto.RegisterType((*CreditAccount)(nil), "liftedinit.billing.v1.CreditAccount")
}

func init() { proto.RegisterFile("liftedinit/billing/v1/types.proto", fileDescriptor_9636bb21eb29c389) }

var fileDescriptor_9636bb21eb29c389 = []byte{
	// 934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0xd3, 0x26, 0x34, 0x93, 0xed, 0x6e, 0x99, 0x66, 0x5b, 0xb7, 0xbb, 0x6b, 0xb7, 0x05,
	0xb1, 0x55, 0xd5, 0xb5, 0xd5, 0xc0, 0x85, 0x72, 0x72, 0xd2, 0x20, 0x45, 0xaa, 0x56, 0x21, 0x49,
	0x41, 0x02, 0x21, 0x6b, 0x62, 0x4f, 0xc3, 0xa8, 0xb6, 0x27, 0x78, 0x26, 0xd9, 0xf6, 0x1f, 0x20,
	0x0e, 0x68, 0x7f, 0x02, 0x12, 0x57, 0x0e, 0x1c, 0xf8, 0x11, 0x7b, 0x5c, 0x71, 0xe2, 0x64, 0x50,
	0x7b, 0x00, 0x59, 0xe2, 0xc4, 0x1f, 0x40, 0x9e, 0x99, 0x26, 0x69, 0x13, 0x28, 0xd2, 0x5e, 0xda,
	0xbc, 0xf7, 0xbe, 0xf7, 0xf9, 0x7b, 0xcf, 0x5f, 0x5e, 0xc0, 0x76, 0x40, 0x4e, 0x39, 0xf6, 0x49,
	0x44, 0xb8, 0xdd, 0x23, 0x41, 0x40, 0xa2, 0xbe, 0x3d, 0x3a, 0xb0, 0xf9, 0xc5, 0x00, 0x33, 0x6b,
	0x10, 0x53, 0x4e, 0xe1, 0xc3, 0x09, 0xc4, 0x52, 0x10, 0x6b, 0x74, 0xb0, 0xf9, 0x36, 0x0a, 0x49,
	0x44, 0x6d, 0xf1, 0x57, 0x22, 0x37, 0x0d, 0x8f, 0xb2, 0x90, 0x32, 0xbb, 0x87, 0x18, 0xb6, 0x47,
	0x07, 0x3d, 0xcc, 0xd1, 0x81, 0xed, 0x51, 0x12, 0xa9, 0xfa, 0x86, 0xac, 0xbb, 0x22, 0xb2, 0x65,
	0xa0, 0x4a, 0x95, 0x3e, 0xed, 0x53, 0x99, 0xcf, 0x3e, 0xa9, 0xac, 0xd9, 0xa7, 0xb4, 0x1f, 0x60,
	0x5b, 0x44, 0xbd, 0xe1, 0xa9, 0xcd, 0x49, 0x88, 0x19, 0x47, 0xe1, 0x40, 0x02, 0x76, 0xbe, 0x5b,
	0x00, 0xc5, 0x16, 0x8a, 0x51, 0xc8, 0xe0, 0x97, 0xe0, 0x61, 0x88, 0xce, 0xdd, 0x00, 0x23, 0x86,
	0x99, 0x3b, 0xc0, 0xb1, 0xcb, 0x71, 0x84, 0x22, 0xae, 0x2f, 0x6c, 0x69, 0xbb, 0x8b, 0xb5, 0xbd,
	0x34, 0x31, 0xdf, 0x9b, 0x0b, 0xd8, 0xa7, 0x21, 0xe1, 0x38, 0x1c, 0xf0, 0x8b, 0x7d, 0xc6, 0x63,
	0x12, 0xf5, 0xdb, 0x30, 0x44, 0xe7, 0xc7, 0x02, 0xd6, 0xc2, 0x71, 0x57, 0x80, 0xe0, 0x09, 0xb8,
	0x87, 0x82, 0x80, 0xbe, 0xc0, 0xbe, 0x1b, 0x10, 0xc6, 0xf5, 0xc5, 0xad, 0x85, 0xdd, 0x52, 0xad,
	0x9a, 0x26, 0xe6, 0xda, 0x74, 0x7e, 0x42, 0xf6, 0xcb, 0xcf, 0xcf, 0x2a, 0x6a, 0x44, 0xc7, 0xf7,
	0x63, 0xcc, 0x58, 0x47, 0xb2, 0x97, 0x15, 0xfe, 0x98, 0x30, 0x0e, 0x3f, 0x03, 0xab, 0x99, 0xa8,
	0xac, 0x47, 0x6a, 0x12, 0xf2, 0xf4, 0x82, 0xd0, 0xbc, 0x9b, 0x26, 0xe6, 0xbb, 0x73, 0xca, 0xb3,
	0x8a, 0x57, 0x42, 0x74, 0xde, 0xcc, 0x40, 0x2d, 0x1c, 0x0b, 0xe5, 0xf0, 0x04, 0xc0, 0x90, 0x44,
	0x12, 0xef, 0xfa, 0xc3, 0x18, 0x71, 0x42, 0x23, 0xbd, 0x28, 0x78, 0x9f, 0xa6, 0x89, 0xf9, 0xce,
	0x6c, 0x75, 0x1e, 0x2d, 0x89, 0x04, 0xdd, 0x91, 0x82, 0x1c, 0x1a, 0x7f, 0x7e, 0x6f, 0x6a, 0xdf,
	0xfe, 0xf1, 0xd3, 0x9e, 0x72, 0xc5, 0xd8, 0x34, 0xf2, 0x2d, 0xec, 0xfc, 0xa5, 0x81, 0x92, 0xe8,
	0xc8, 0xd4, 0xc0, 0x2a, 0x28, 0xb2, 0xb3, 0xa1, 0x4b, 0x7c, 0x5d, 0x13, 0x0f, 0x7e, 0x94, 0x26,
	0xe6, 0xba, 0xcc, 0xcc, 0x3e, 0xac, 0xc0, 0xce, 0x86, 0x4d, 0x1f, 0x7e, 0x08, 0x96, 0xbe, 0x1e,
	0xa2, 0x88, 0x13, 0x7e, 0xa1, 0xe7, 0x45, 0xd7, 0x93, 0x34, 0x31, 0x37, 0xae, 0x73, 0xb3, 0x7d,
	0x63, 0x38, 0x6c, 0x83, 0x7b, 0x01, 0xf5, 0xce, 0xb0, 0xef, 0x0e, 0x62, 0xe2, 0x61, 0xf1, 0xe6,
	0xcb, 0xd5, 0x0d, 0x4b, 0xbd, 0x86, 0xcc, 0x96, 0x96, 0xb2, 0xa5, 0x55, 0xa7, 0x24, 0xaa, 0x55,
	0x5e, 0x25, 0x66, 0x2e, 0x4d, 0xcc, 0x1b, 0x6d, 0xed, 0xb2, 0x8c, 0x5a, 0x59, 0x70, 0xf8, 0x24,
	0x1b, 0x56, 0xbf, 0x35, 0xec, 0x78, 0xc2, 0x9d, 0xbf, 0x17, 0x41, 0x41, 0x2e, 0xfc, 0x29, 0xc8,
	0x8f, 0xe7, 0x5c, 0x4f, 0x13, 0x73, 0x75, 0xde, 0x8c, 0x79, 0xe2, 0xc3, 0x23, 0x50, 0x54, 0xce,
	0xcc, 0xc6, 0x2b, 0xd5, 0xf6, 0xd3, 0xc4, 0x5c, 0xb9, 0x6d, 0xc5, 0x7f, 0x75, 0x8f, 0xea, 0x85,
	0x0e, 0x28, 0x0f, 0x62, 0x3a, 0x22, 0x3e, 0x8e, 0xb3, 0xfd, 0x4a, 0x93, 0x6f, 0xa5, 0x89, 0xf9,
	0x78, 0x2a, 0x3d, 0x2b, 0x00, 0x5c, 0x57, 0x9b, 0x3e, 0x6c, 0x80, 0x82, 0x30, 0x96, 0xf0, 0x72,
	0xb9, 0xba, 0x65, 0xcd, 0xfd, 0xa2, 0x5b, 0xe3, 0x61, 0x6b, 0xcb, 0x6a, 0x5d, 0xb2, 0xad, 0x2d,
	0xff, 0xc1, 0x63, 0x50, 0x60, 0x1c, 0x71, 0x69, 0xda, 0xfb, 0xd5, 0xed, 0xff, 0xa2, 0xe9, 0x64,
	0xc0, 0xda, 0x6a, 0x9a, 0x98, 0x0f, 0x44, 0xcf, 0x44, 0x60, 0x5b, 0x92, 0xc0, 0x4f, 0x00, 0xf0,
	0x62, 0x8c, 0x38, 0xf6, 0x5d, 0xc4, 0x85, 0x5f, 0xcb, 0xd5, 0x4d, 0x4b, 0xde, 0x01, 0xeb, 0xfa,
	0x0e, 0x58, 0xdd, 0xeb, 0x3b, 0x50, 0x5b, 0x53, 0x9a, 0xa6, 0xba, 0x5e, 0xfe, 0x66, 0x6a, 0xed,
	0x92, 0x8a, 0x1d, 0x0e, 0xbb, 0xa0, 0xe4, 0x05, 0x94, 0x49, 0xc6, 0xb7, 0xee, 0x64, 0xcc, 0x4c,
	0xba, 0x3a, 0x6e, 0x98, 0x28, 0x14, 0xb4, 0x4b, 0xb2, 0xe0, 0x70, 0xe8, 0x82, 0x07, 0x01, 0x62,
	0xdc, 0x65, 0x98, 0xf3, 0x40, 0x72, 0x2f, 0xdd, 0xcd, 0xad, 0xd4, 0xde, 0x6e, 0x15, 0xdc, 0xcb,
	0x59, 0xb2, 0x23, 0x73, 0x0e, 0x3f, 0xdc, 0xc8, 0x9c, 0x57, 0x99, 0xe7, 0xbc, 0x9d, 0x1f, 0xf3,
	0x60, 0xb9, 0x1e, 0x63, 0x9f, 0x70, 0xc7, 0xf3, 0xe8, 0x30, 0xe2, 0x53, 0xa6, 0xd2, 0xde, 0xc0,
	0x54, 0x5f, 0x80, 0xfb, 0x9e, 0xa0, 0x75, 0x91, 0xac, 0x2b, 0x8b, 0x7e, 0x90, 0x26, 0xa6, 0x7e,
	0xb3, 0xf2, 0x3f, 0x58, 0x97, 0x65, 0x87, 0x4a, 0x66, 0x17, 0x09, 0x79, 0x9c, 0x8c, 0xb0, 0x3a,
	0x3b, 0x42, 0xb8, 0x32, 0xae, 0xb8, 0x48, 0xb3, 0xd5, 0x39, 0x17, 0x49, 0x82, 0xc4, 0x1a, 0xea,
	0x19, 0xe4, 0x70, 0x3b, 0x5b, 0xd3, 0xe3, 0x5b, 0x6b, 0xba, 0xb1, 0x9c, 0x3d, 0x04, 0xc0, 0xc4,
	0x7d, 0xf0, 0x11, 0x58, 0x3f, 0x6e, 0x38, 0x9d, 0x86, 0xdb, 0xe9, 0x3a, 0xdd, 0x86, 0x7b, 0xf2,
	0xbc, 0xd3, 0x6a, 0xd4, 0x9b, 0x1f, 0x37, 0x1b, 0x47, 0x2b, 0x39, 0xb8, 0x06, 0xe0, 0x74, 0xd1,
	0xa9, 0x77, 0x9b, 0x9f, 0x36, 0x56, 0x34, 0xa8, 0x83, 0xca, 0x74, 0xbe, 0xf9, 0x5c, 0x55, 0xf2,
	0x9b, 0x8b, 0xdf, 0xfc, 0x60, 0xe4, 0x6a, 0x27, 0xaf, 0x2e, 0x0d, 0xed, 0xf5, 0xa5, 0xa1, 0xfd,
	0x7e, 0x69, 0x68, 0x2f, 0xaf, 0x8c, 0xdc, 0xeb, 0x2b, 0x23, 0xf7, 0xeb, 0x95, 0x91, 0xfb, 0xfc,
	0xa3, 0x3e, 0xe1, 0x5f, 0x0d, 0x7b, 0x96, 0x47, 0x43, 0x3b, 0x44, 0x11, 0x39, 0xc5, 0x8c, 0x3f,
	0x8b, 0x30, 0x7f, 0x41, 0xe3, 0xb3, 0x49, 0x22, 0xc0, 0x7e, 0x1f, 0xc7, 0xf6, 0xf9, 0x78, 0x02,
	0xf1, 0x0b, 0xdc, 0x2b, 0x0a, 0x0f, 0xbd, 0xff, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x0d,
	0x32, 0xcc, 0xa7, 0x07, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxLeasesPerTenant != that1.MaxLeasesPerTenant {
		return false
	}
	if len(this.AllowedList) != len(that1.AllowedList) {
		return false
	}
	for i := range this.AllowedList {
		if this.AllowedList[i] != that1.AllowedList[i] {
			return false
		}
	}
	if this.MaxItemsPerLease != that1.MaxItemsPerLease {
		return false
	}
	if this.MinLeaseDuration != that1.MinLeaseDuration {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinLeaseDuration != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MinLeaseDuration))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxItemsPerLease != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxItemsPerLease))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AllowedList) > 0 {
		for iNdEx := len(m.AllowedList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedList[iNdEx])
			copy(dAtA[i:], m.AllowedList[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.AllowedList[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.MaxLeasesPerTenant != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxLeasesPerTenant))
		i--
		dAtA[i] = 0x18
	}
	return len(dAtA) - i, nil
}

func (m *LeaseItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LeaseItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeaseItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LockedPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Quantity != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x10
	}
	if m.SkuId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SkuId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Lease) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Lease) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Lease) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastSettledAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastSettledAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTypes(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x42
	if m.ClosedAt != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ClosedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ClosedAt):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintTypes(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x3a
	}
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintTypes(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x32
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ProviderId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ProviderId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CreditAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreditAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreditAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActiveLeaseCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ActiveLeaseCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CreditAddress) > 0 {
		i -= len(m.CreditAddress)
		copy(dAtA[i:], m.CreditAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreditAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxLeasesPerTenant != 0 {
		n += 1 + sovTypes(uint64(m.MaxLeasesPerTenant))
	}
	if len(m.AllowedList) > 0 {
		for _, s := range m.AllowedList {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.MaxItemsPerLease != 0 {
		n += 1 + sovTypes(uint64(m.MaxItemsPerLease))
	}
	if m.MinLeaseDuration != 0 {
		n += 1 + sovTypes(uint64(m.MinLeaseDuration))
	}
	return n
}

func (m *LeaseItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SkuId != 0 {
		n += 1 + sovTypes(uint64(m.SkuId))
	}
	if m.Quantity != 0 {
		n += 1 + sovTypes(uint64(m.Quantity))
	}
	l = m.LockedPrice.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *Lease) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ProviderId != 0 {
		n += 1 + sovTypes(uint64(m.ProviderId))
	}
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovTypes(uint64(l))
	if m.ClosedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ClosedAt)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastSettledAt)
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *CreditAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreditAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ActiveLeaseCount != 0 {
		n += 1 + sovTypes(uint64(m.ActiveLeaseCount))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLeasesPerTenant", wireType)
			}
			m.MaxLeasesPerTenant = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLeasesPerTenant |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedList = append(m.AllowedList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxItemsPerLease", wireType)
			}
			m.MaxItemsPerLease = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxItemsPerLease |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLeaseDuration", wireType)
			}
			m.MinLeaseDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLeaseDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LeaseItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LeaseItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LeaseItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkuId", wireType)
			}
			m.SkuId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SkuId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LockedPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Lease) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Lease: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Lease: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderId", wireType)
			}
			m.ProviderId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProviderId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, LeaseItem{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= LeaseState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClosedAt == nil {
				m.ClosedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ClosedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSettledAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastSettledAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreditAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreditAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreditAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreditAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveLeaseCount", wireType)
			}
			m.ActiveLeaseCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveLeaseCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
