// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: liftedinit/billing/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LeaseState defines the state of a lease.
type LeaseState int32

const (
	// LEASE_STATE_UNSPECIFIED is the default value.
	LEASE_STATE_UNSPECIFIED LeaseState = 0
	// LEASE_STATE_PENDING indicates the lease is awaiting provider acknowledgement.
	// Credit is locked but billing has not started.
	LEASE_STATE_PENDING LeaseState = 1
	// LEASE_STATE_ACTIVE indicates the lease is active and accruing charges.
	// Provider has acknowledged and resources are provisioned.
	LEASE_STATE_ACTIVE LeaseState = 2
	// LEASE_STATE_CLOSED indicates the lease has been closed normally.
	// Final settlement has occurred.
	LEASE_STATE_CLOSED LeaseState = 3
	// LEASE_STATE_REJECTED indicates the provider rejected the lease.
	// Credit has been unlocked and returned to tenant.
	LEASE_STATE_REJECTED LeaseState = 4
	// LEASE_STATE_EXPIRED indicates the lease expired while in PENDING state.
	// Provider did not acknowledge within the timeout period.
	// Credit has been unlocked and returned to tenant.
	LEASE_STATE_EXPIRED LeaseState = 5
)

var LeaseState_name = map[int32]string{
	0: "LEASE_STATE_UNSPECIFIED",
	1: "LEASE_STATE_PENDING",
	2: "LEASE_STATE_ACTIVE",
	3: "LEASE_STATE_CLOSED",
	4: "LEASE_STATE_REJECTED",
	5: "LEASE_STATE_EXPIRED",
}

var LeaseState_value = map[string]int32{
	"LEASE_STATE_UNSPECIFIED": 0,
	"LEASE_STATE_PENDING":     1,
	"LEASE_STATE_ACTIVE":      2,
	"LEASE_STATE_CLOSED":      3,
	"LEASE_STATE_REJECTED":    4,
	"LEASE_STATE_EXPIRED":     5,
}

func (x LeaseState) String() string {
	return proto.EnumName(LeaseState_name, int32(x))
}

func (LeaseState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{0}
}

// Params defines the parameters for the billing module.
type Params struct {
	// max_leases_per_tenant is the maximum number of active leases a tenant can have.
	// Must be greater than zero.
	MaxLeasesPerTenant uint64 `protobuf:"varint,3,opt,name=max_leases_per_tenant,json=maxLeasesPerTenant,proto3" json:"max_leases_per_tenant,omitempty,string"`
	// allowed_list is the list of addresses allowed to create leases on behalf of tenants
	// in addition to the module authority.
	AllowedList []string `protobuf:"bytes,4,rep,name=allowed_list,json=allowedList,proto3" json:"allowed_list,omitempty"`
	// max_items_per_lease is the maximum number of items (SKUs) allowed in a single lease.
	// Must be greater than zero. Prevents excessive gas consumption from large leases.
	MaxItemsPerLease uint64 `protobuf:"varint,5,opt,name=max_items_per_lease,json=maxItemsPerLease,proto3" json:"max_items_per_lease,omitempty,string"`
	// min_lease_duration is the minimum duration (in seconds) that a tenant's credit balance
	// must be able to cover when creating a lease. This prevents tenants from creating leases
	// that would immediately exhaust their credit. Default is 3600 (1 hour).
	MinLeaseDuration uint64 `protobuf:"varint,6,opt,name=min_lease_duration,json=minLeaseDuration,proto3" json:"min_lease_duration,omitempty,string"`
	// max_pending_leases_per_tenant is the maximum number of PENDING leases a tenant can have.
	// Prevents spam attacks where tenants create many leases that providers must process.
	// Default is 10.
	MaxPendingLeasesPerTenant uint64 `protobuf:"varint,7,opt,name=max_pending_leases_per_tenant,json=maxPendingLeasesPerTenant,proto3" json:"max_pending_leases_per_tenant,omitempty,string"`
	// pending_timeout is the duration in seconds that a lease can remain in PENDING state
	// before it expires. Applies globally to all providers. Default is 1800 (30 minutes).
	// Must be between 60 (1 minute) and 86400 (24 hours).
	PendingTimeout uint64 `protobuf:"varint,8,opt,name=pending_timeout,json=pendingTimeout,proto3" json:"pending_timeout,omitempty,string"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxLeasesPerTenant() uint64 {
	if m != nil {
		return m.MaxLeasesPerTenant
	}
	return 0
}

func (m *Params) GetAllowedList() []string {
	if m != nil {
		return m.AllowedList
	}
	return nil
}

func (m *Params) GetMaxItemsPerLease() uint64 {
	if m != nil {
		return m.MaxItemsPerLease
	}
	return 0
}

func (m *Params) GetMinLeaseDuration() uint64 {
	if m != nil {
		return m.MinLeaseDuration
	}
	return 0
}

func (m *Params) GetMaxPendingLeasesPerTenant() uint64 {
	if m != nil {
		return m.MaxPendingLeasesPerTenant
	}
	return 0
}

func (m *Params) GetPendingTimeout() uint64 {
	if m != nil {
		return m.PendingTimeout
	}
	return 0
}

// LeaseItem represents a single SKU item within a lease.
type LeaseItem struct {
	// sku_uuid is the UUID of the SKU being leased.
	SkuUuid string `protobuf:"bytes,1,opt,name=sku_uuid,json=skuUuid,proto3" json:"sku_uuid,omitempty"`
	// quantity is the number of instances of this SKU.
	Quantity uint64 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty,string"`
	// locked_price is the price per unit locked at lease creation (per second).
	// The denom comes from the SKU's base_price at lease creation time.
	LockedPrice types.Coin `protobuf:"bytes,3,opt,name=locked_price,json=lockedPrice,proto3" json:"locked_price"`
	// service_name is an optional DNS-label identifier for this item within a stack deployment.
	// When used, all items must have a service_name and uniqueness shifts from sku_uuid to service_name,
	// allowing the same SKU to appear multiple times (e.g., "web" and "db" both using docker-small).
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (m *LeaseItem) Reset()         { *m = LeaseItem{} }
func (m *LeaseItem) String() string { return proto.CompactTextString(m) }
func (*LeaseItem) ProtoMessage()    {}
func (*LeaseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{1}
}
func (m *LeaseItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LeaseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LeaseItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LeaseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseItem.Merge(m, src)
}
func (m *LeaseItem) XXX_Size() int {
	return m.Size()
}
func (m *LeaseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseItem.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseItem proto.InternalMessageInfo

func (m *LeaseItem) GetSkuUuid() string {
	if m != nil {
		return m.SkuUuid
	}
	return ""
}

func (m *LeaseItem) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *LeaseItem) GetLockedPrice() types.Coin {
	if m != nil {
		return m.LockedPrice
	}
	return types.Coin{}
}

func (m *LeaseItem) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

// Lease represents a billing lease between a tenant and provider.
type Lease struct {
	// uuid is the unique identifier of the lease (UUIDv7 format).
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// tenant is the address of the tenant who owns this lease.
	Tenant string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// provider_uuid is the provider UUID (denormalized from SKUs for efficient querying).
	ProviderUuid string `protobuf:"bytes,3,opt,name=provider_uuid,json=providerUuid,proto3" json:"provider_uuid,omitempty"`
	// items is the list of SKU items in this lease.
	Items []LeaseItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items"`
	// state is the current state of the lease.
	State LeaseState `protobuf:"varint,5,opt,name=state,proto3,enum=liftedinit.billing.v1.LeaseState" json:"state,omitempty"`
	// created_at is the timestamp when the lease was created.
	// Credit is locked at this time.
	CreatedAt time.Time `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// closed_at is the timestamp when the lease was closed (if CLOSED state).
	ClosedAt *time.Time `protobuf:"bytes,7,opt,name=closed_at,json=closedAt,proto3,stdtime" json:"closed_at,omitempty"`
	// last_settled_at is the timestamp of the last settlement/withdrawal.
	// Only applicable for ACTIVE and CLOSED states.
	LastSettledAt time.Time `protobuf:"bytes,8,opt,name=last_settled_at,json=lastSettledAt,proto3,stdtime" json:"last_settled_at"`
	// acknowledged_at is the timestamp when the provider acknowledged the lease.
	// Only set when state transitions from PENDING to ACTIVE.
	// Billing starts from this timestamp.
	AcknowledgedAt *time.Time `protobuf:"bytes,9,opt,name=acknowledged_at,json=acknowledgedAt,proto3,stdtime" json:"acknowledged_at,omitempty"`
	// rejected_at is the timestamp when the provider rejected the lease.
	// Only set when state is REJECTED.
	RejectedAt *time.Time `protobuf:"bytes,10,opt,name=rejected_at,json=rejectedAt,proto3,stdtime" json:"rejected_at,omitempty"`
	// rejection_reason is a free-form explanation for why the lease was rejected.
	// Only set when state is REJECTED. Maximum 256 characters.
	RejectionReason string `protobuf:"bytes,11,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// expired_at is the timestamp when the lease expired while in PENDING state.
	// Only set when state is EXPIRED.
	ExpiredAt *time.Time `protobuf:"bytes,12,opt,name=expired_at,json=expiredAt,proto3,stdtime" json:"expired_at,omitempty"`
	// closure_reason is a free-form explanation for why the lease was closed.
	// Only set when state is CLOSED. Maximum 256 characters.
	ClosureReason string `protobuf:"bytes,13,opt,name=closure_reason,json=closureReason,proto3" json:"closure_reason,omitempty"`
	// meta_hash is an optional hash/reference to off-chain deployment data.
	// Set once at lease creation and immutable. Maximum 64 bytes.
	MetaHash []byte `protobuf:"bytes,14,opt,name=meta_hash,json=metaHash,proto3" json:"meta_hash,omitempty"`
	// min_lease_duration_at_creation stores the min_lease_duration parameter value
	// at the time this lease was created. This ensures consistent reservation
	// calculation regardless of subsequent parameter changes.
	// reservation = sum(locked_price × quantity) × min_lease_duration_at_creation
	MinLeaseDurationAtCreation uint64 `protobuf:"varint,15,opt,name=min_lease_duration_at_creation,json=minLeaseDurationAtCreation,proto3" json:"min_lease_duration_at_creation,omitempty,string"`
}

func (m *Lease) Reset()         { *m = Lease{} }
func (m *Lease) String() string { return proto.CompactTextString(m) }
func (*Lease) ProtoMessage()    {}
func (*Lease) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{2}
}
func (m *Lease) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Lease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Lease.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Lease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lease.Merge(m, src)
}
func (m *Lease) XXX_Size() int {
	return m.Size()
}
func (m *Lease) XXX_DiscardUnknown() {
	xxx_messageInfo_Lease.DiscardUnknown(m)
}

var xxx_messageInfo_Lease proto.InternalMessageInfo

func (m *Lease) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Lease) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Lease) GetProviderUuid() string {
	if m != nil {
		return m.ProviderUuid
	}
	return ""
}

func (m *Lease) GetItems() []LeaseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Lease) GetState() LeaseState {
	if m != nil {
		return m.State
	}
	return LEASE_STATE_UNSPECIFIED
}

func (m *Lease) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *Lease) GetClosedAt() *time.Time {
	if m != nil {
		return m.ClosedAt
	}
	return nil
}

func (m *Lease) GetLastSettledAt() time.Time {
	if m != nil {
		return m.LastSettledAt
	}
	return time.Time{}
}

func (m *Lease) GetAcknowledgedAt() *time.Time {
	if m != nil {
		return m.AcknowledgedAt
	}
	return nil
}

func (m *Lease) GetRejectedAt() *time.Time {
	if m != nil {
		return m.RejectedAt
	}
	return nil
}

func (m *Lease) GetRejectionReason() string {
	if m != nil {
		return m.RejectionReason
	}
	return ""
}

func (m *Lease) GetExpiredAt() *time.Time {
	if m != nil {
		return m.ExpiredAt
	}
	return nil
}

func (m *Lease) GetClosureReason() string {
	if m != nil {
		return m.ClosureReason
	}
	return ""
}

func (m *Lease) GetMetaHash() []byte {
	if m != nil {
		return m.MetaHash
	}
	return nil
}

func (m *Lease) GetMinLeaseDurationAtCreation() uint64 {
	if m != nil {
		return m.MinLeaseDurationAtCreation
	}
	return 0
}

// CreditAccount represents a tenant's credit account.
// The actual balance is tracked by the bank module at the credit_address.
type CreditAccount struct {
	// tenant is the address of the tenant who owns this credit account.
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// credit_address is the derived address where credit funds are held.
	CreditAddress string `protobuf:"bytes,2,opt,name=credit_address,json=creditAddress,proto3" json:"credit_address,omitempty"`
	// active_lease_count tracks the number of active leases for O(1) count queries.
	ActiveLeaseCount uint64 `protobuf:"varint,3,opt,name=active_lease_count,json=activeLeaseCount,proto3" json:"active_lease_count,omitempty,string"`
	// pending_lease_count tracks the number of pending leases for O(1) count queries.
	// Used to enforce max_pending_leases_per_tenant limit.
	PendingLeaseCount uint64 `protobuf:"varint,4,opt,name=pending_lease_count,json=pendingLeaseCount,proto3" json:"pending_lease_count,omitempty,string"`
	// reserved_amounts holds the sum of all credit reservations for active and pending leases.
	// Each lease reserves: rate_per_second × min_lease_duration for each denom.
	// This prevents overbooking by ensuring credit availability before lease creation.
	ReservedAmounts github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=reserved_amounts,json=reservedAmounts,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"reserved_amounts"`
}

func (m *CreditAccount) Reset()         { *m = CreditAccount{} }
func (m *CreditAccount) String() string { return proto.CompactTextString(m) }
func (*CreditAccount) ProtoMessage()    {}
func (*CreditAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9636bb21eb29c389, []int{3}
}
func (m *CreditAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreditAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreditAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreditAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditAccount.Merge(m, src)
}
func (m *CreditAccount) XXX_Size() int {
	return m.Size()
}
func (m *CreditAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CreditAccount proto.InternalMessageInfo

func (m *CreditAccount) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *CreditAccount) GetCreditAddress() string {
	if m != nil {
		return m.CreditAddress
	}
	return ""
}

func (m *CreditAccount) GetActiveLeaseCount() uint64 {
	if m != nil {
		return m.ActiveLeaseCount
	}
	return 0
}

func (m *CreditAccount) GetPendingLeaseCount() uint64 {
	if m != nil {
		return m.PendingLeaseCount
	}
	return 0
}

func (m *CreditAccount) GetReservedAmounts() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.ReservedAmounts
	}
	return nil
}

func init() {
	proto.RegisterEnum("liftedinit.billing.v1.LeaseState", LeaseState_name, LeaseState_value)
	proto.RegisterType((*Params)(nil), "liftedinit.billing.v1.Params")
	proto.RegisterType((*LeaseItem)(nil), "liftedinit.billing.v1.LeaseItem")
	proto.RegisterType((*Lease)(nil), "liftedinit.billing.v1.Lease")
	proto.RegisterType((*CreditAccount)(nil), "liftedinit.billing.v1.CreditAccount")
}

func init() { proto.RegisterFile("liftedinit/billing/v1/types.proto", fileDescriptor_9636bb21eb29c389) }

var fileDescriptor_9636bb21eb29c389 = []byte{
	// 1332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5d, 0x4f, 0x1b, 0x47,
	0x17, 0xc6, 0x60, 0x08, 0x1e, 0x63, 0xe3, 0x0c, 0x04, 0x16, 0x27, 0xf1, 0x02, 0x6f, 0x94, 0x17,
	0x45, 0x89, 0x2d, 0x48, 0x6e, 0x5e, 0x5e, 0x55, 0xaa, 0x3f, 0xb6, 0xad, 0x2b, 0x4a, 0x5d, 0xdb,
	0x34, 0x51, 0xaa, 0x6a, 0x35, 0xec, 0x0e, 0x66, 0x8a, 0x77, 0xd7, 0xdd, 0x19, 0x03, 0xf9, 0x07,
	0x55, 0xae, 0x22, 0xf5, 0x0f, 0x54, 0xea, 0x5d, 0x73, 0xd3, 0x8b, 0xfe, 0x88, 0xdc, 0x54, 0x8a,
	0xda, 0x9b, 0x5e, 0x6d, 0xaa, 0xe4, 0xa2, 0xd5, 0xfe, 0x8a, 0x6a, 0x3e, 0x6c, 0x2f, 0x6b, 0x17,
	0x2a, 0xf5, 0x06, 0x33, 0xe7, 0x79, 0xce, 0x33, 0xcf, 0x9e, 0x3d, 0x73, 0x66, 0xc1, 0x46, 0x97,
	0x1c, 0x31, 0x6c, 0x13, 0x97, 0xb0, 0xd2, 0x21, 0xe9, 0x76, 0x89, 0xdb, 0x29, 0x9d, 0x6e, 0x97,
	0xd8, 0xb3, 0x1e, 0xa6, 0xc5, 0x9e, 0xef, 0x31, 0x0f, 0xde, 0x18, 0x51, 0x8a, 0x8a, 0x52, 0x3c,
	0xdd, 0xce, 0x5f, 0x47, 0x0e, 0x71, 0xbd, 0x92, 0xf8, 0x2b, 0x99, 0xf9, 0x82, 0xe5, 0x51, 0xc7,
	0xa3, 0xa5, 0x43, 0x44, 0x71, 0xe9, 0x74, 0xfb, 0x10, 0x33, 0xb4, 0x5d, 0xb2, 0x3c, 0xe2, 0x2a,
	0x7c, 0x4d, 0xe2, 0xa6, 0x58, 0x95, 0xe4, 0x42, 0x41, 0xcb, 0x1d, 0xaf, 0xe3, 0xc9, 0x38, 0xff,
	0x4f, 0x45, 0xf5, 0x8e, 0xe7, 0x75, 0xba, 0xb8, 0x24, 0x56, 0x87, 0xfd, 0xa3, 0x12, 0x23, 0x0e,
	0xa6, 0x0c, 0x39, 0x3d, 0x49, 0xd8, 0xfc, 0x35, 0x09, 0xe6, 0x1a, 0xc8, 0x47, 0x0e, 0x85, 0x5f,
	0x82, 0x1b, 0x0e, 0x3a, 0x37, 0xbb, 0x18, 0x51, 0x4c, 0xcd, 0x1e, 0xf6, 0x4d, 0x86, 0x5d, 0xe4,
	0x32, 0x6d, 0x66, 0x3d, 0xb1, 0x95, 0xac, 0xdc, 0x0b, 0x03, 0xfd, 0xee, 0x44, 0xc2, 0x7d, 0xcf,
	0x21, 0x0c, 0x3b, 0x3d, 0xf6, 0xec, 0x3e, 0x65, 0x3e, 0x71, 0x3b, 0x4d, 0xe8, 0xa0, 0xf3, 0x3d,
	0x41, 0x6b, 0x60, 0xbf, 0x2d, 0x48, 0xf0, 0x00, 0x2c, 0xa0, 0x6e, 0xd7, 0x3b, 0xc3, 0xb6, 0xd9,
	0x25, 0x94, 0x69, 0xc9, 0xf5, 0x99, 0xad, 0x54, 0x65, 0x27, 0x0c, 0xf4, 0x95, 0x68, 0x7c, 0x24,
	0xf6, 0xcb, 0x4f, 0x0f, 0x96, 0xd5, 0x23, 0x96, 0x6d, 0xdb, 0xc7, 0x94, 0xb6, 0xa4, 0x7a, 0x5a,
	0xf1, 0xf7, 0x08, 0x65, 0xf0, 0x31, 0x58, 0xe2, 0xa6, 0x78, 0x8e, 0xf4, 0x24, 0xec, 0x69, 0xb3,
	0xc2, 0xf3, 0x56, 0x18, 0xe8, 0x77, 0x26, 0xc0, 0xe3, 0x8e, 0x73, 0x0e, 0x3a, 0xaf, 0x73, 0x52,
	0x03, 0xfb, 0xc2, 0x39, 0x3c, 0x00, 0xd0, 0x21, 0xae, 0xe4, 0x9b, 0x76, 0xdf, 0x47, 0x8c, 0x78,
	0xae, 0x36, 0x27, 0x74, 0xff, 0x1b, 0x06, 0xfa, 0x7f, 0xc6, 0xd1, 0x49, 0xb2, 0xc4, 0x15, 0x72,
	0x35, 0x45, 0x81, 0x0c, 0xdc, 0xe6, 0x86, 0x7a, 0xd8, 0xb5, 0x89, 0xdb, 0x99, 0x50, 0xed, 0x6b,
	0x62, 0x07, 0x5e, 0x97, 0xe2, 0xa5, 0xc4, 0xf1, 0xcd, 0xd6, 0x1c, 0x74, 0xde, 0x90, 0xf4, 0x78,
	0xf1, 0x3f, 0x01, 0x8b, 0x03, 0x21, 0xde, 0x01, 0x5e, 0x9f, 0x69, 0xf3, 0x62, 0x9f, 0x3b, 0x61,
	0xa0, 0xaf, 0xc7, 0xa0, 0x71, 0xe5, 0xac, 0x62, 0xb4, 0x25, 0x61, 0xb7, 0xf0, 0xe7, 0x77, 0x7a,
	0xe2, 0xf9, 0x1f, 0x3f, 0xde, 0x53, 0xad, 0x3d, 0xec, 0x7c, 0xd9, 0x4a, 0x9b, 0x2f, 0xa7, 0x41,
	0x4a, 0x58, 0xe0, 0x25, 0x85, 0xdb, 0x60, 0x9e, 0x9e, 0xf4, 0xcd, 0x7e, 0x9f, 0xd8, 0x5a, 0x62,
	0x3d, 0xb1, 0x95, 0xaa, 0xac, 0x84, 0x81, 0x0e, 0x07, 0xb1, 0xd1, 0x76, 0xcd, 0x6b, 0xf4, 0xa4,
	0x7f, 0xd0, 0x27, 0x36, 0xfc, 0x1f, 0x98, 0xff, 0xba, 0x8f, 0x5c, 0x46, 0xd8, 0x33, 0x6d, 0x5a,
	0x18, 0xbd, 0x1d, 0x06, 0xfa, 0xda, 0x20, 0x36, 0xee, 0x70, 0x48, 0x87, 0x4d, 0xb0, 0xd0, 0xf5,
	0xac, 0x13, 0x6c, 0x9b, 0x3d, 0x9f, 0x58, 0x58, 0x74, 0x6f, 0x7a, 0x67, 0xad, 0xa8, 0x5a, 0x89,
	0x1f, 0xad, 0xa2, 0x3a, 0x5a, 0xc5, 0xaa, 0x47, 0xdc, 0xca, 0xf2, 0xab, 0x40, 0x9f, 0x0a, 0x03,
	0xfd, 0x42, 0x5a, 0x33, 0x2d, 0x57, 0x0d, 0xbe, 0x80, 0xef, 0x81, 0x05, 0x8a, 0xfd, 0x53, 0x62,
	0x61, 0xd3, 0x45, 0x0e, 0xd6, 0x92, 0xe2, 0x29, 0xf2, 0xbc, 0x77, 0xa3, 0xf1, 0xc8, 0x93, 0xa4,
	0x55, 0x7c, 0x1f, 0x39, 0x78, 0xf7, 0x36, 0x2f, 0x95, 0x16, 0x2b, 0xd5, 0xb0, 0x3e, 0x9b, 0x3f,
	0xa7, 0xc0, 0xac, 0xec, 0xb9, 0xbb, 0x20, 0x19, 0xa9, 0x12, 0x0c, 0x03, 0x3d, 0x1b, 0xab, 0x90,
	0xc0, 0x61, 0x0d, 0xcc, 0xa9, 0x6e, 0x99, 0x16, 0xcc, 0xfb, 0x61, 0xa0, 0xe7, 0xe2, 0x6d, 0xf1,
	0xb7, 0xe7, 0x47, 0xe5, 0xc2, 0xf7, 0x41, 0xa6, 0xe7, 0x7b, 0xa7, 0xc4, 0xc6, 0xbe, 0x7c, 0x39,
	0x33, 0x42, 0xec, 0x66, 0x18, 0xe8, 0xab, 0x17, 0x80, 0xc8, 0xfe, 0x0b, 0x03, 0x40, 0xbc, 0x26,
	0x03, 0xcc, 0x8a, 0x93, 0x25, 0x0e, 0x73, 0x7a, 0x67, 0xbd, 0x38, 0x71, 0xd2, 0x15, 0x87, 0x8f,
	0x5a, 0xc9, 0xa8, 0x5a, 0xcb, 0xb4, 0xa6, 0xfc, 0x81, 0x7b, 0x60, 0x96, 0x32, 0xc4, 0xe4, 0xa9,
	0xcd, 0xee, 0x6c, 0x5c, 0x26, 0xd3, 0xe2, 0xc4, 0xca, 0x52, 0x18, 0xe8, 0x8b, 0x22, 0x27, 0xe2,
	0x4d, 0x8a, 0xc0, 0xcf, 0x00, 0xb0, 0x7c, 0x8c, 0x18, 0xb6, 0x4d, 0xc4, 0xc4, 0x81, 0x4d, 0xef,
	0xe4, 0x8b, 0x72, 0x10, 0x16, 0x07, 0x83, 0xb0, 0xd8, 0x1e, 0x0c, 0xc2, 0xca, 0x8a, 0xf2, 0x14,
	0xc9, 0x7a, 0xf1, 0x46, 0x4f, 0x34, 0x53, 0x6a, 0x5d, 0x66, 0xb0, 0x0d, 0x52, 0x56, 0xd7, 0xa3,
	0x52, 0xf1, 0xda, 0x95, 0x8a, 0xbc, 0x82, 0x4b, 0xc3, 0x84, 0x91, 0x43, 0x21, 0x3b, 0x2f, 0x81,
	0x32, 0x83, 0x26, 0x58, 0xec, 0x22, 0xca, 0x4c, 0x8a, 0x19, 0xeb, 0x4a, 0xed, 0xf9, 0xab, 0xb5,
	0x95, 0xdb, 0x78, 0xaa, 0xd0, 0xce, 0xf0, 0x60, 0x4b, 0xc6, 0xca, 0x0c, 0x1e, 0x81, 0x45, 0x64,
	0x9d, 0xb8, 0xde, 0x59, 0x17, 0xdb, 0x1d, 0xb9, 0x41, 0xea, 0xca, 0x0d, 0x36, 0xf8, 0x41, 0x8b,
	0xa5, 0xc5, 0x1e, 0x21, 0x1b, 0x85, 0xcb, 0x0c, 0x3e, 0x05, 0x69, 0x1f, 0x7f, 0x85, 0x2d, 0x55,
	0x72, 0x70, 0xe5, 0x1e, 0xfc, 0x30, 0xdf, 0x88, 0xa4, 0xc4, 0xf4, 0xc1, 0x00, 0x2a, 0x33, 0x58,
	0x07, 0x39, 0xb9, 0x22, 0x9e, 0x6b, 0xfa, 0x18, 0x51, 0xcf, 0xd5, 0xd2, 0xa2, 0x4f, 0x0b, 0x61,
	0xa0, 0xe7, 0xe3, 0x58, 0xa4, 0x1d, 0x16, 0x87, 0x58, 0x53, 0x40, 0xf0, 0x31, 0x00, 0xf8, 0xbc,
	0x47, 0x7c, 0xe9, 0x72, 0xe1, 0x4a, 0x97, 0xb7, 0xc2, 0x40, 0x5f, 0x1e, 0x65, 0xc4, 0x4c, 0xa6,
	0x14, 0x52, 0x66, 0xb0, 0x0a, 0xb2, 0xfc, 0xa5, 0xf6, 0x7d, 0x3c, 0x70, 0x98, 0x11, 0x0e, 0xb9,
	0x80, 0x76, 0x11, 0x89, 0xf8, 0xcb, 0x28, 0x44, 0xb9, 0x7b, 0x04, 0x52, 0x0e, 0x66, 0xc8, 0x3c,
	0x46, 0xf4, 0x58, 0xcb, 0xae, 0x27, 0xb6, 0x16, 0x2a, 0xab, 0xbc, 0x8f, 0x86, 0xc1, 0x48, 0xea,
	0x3c, 0x0f, 0x7e, 0x84, 0xe8, 0x31, 0x3c, 0x03, 0x85, 0xf1, 0x7b, 0xc8, 0x44, 0xcc, 0x14, 0xcd,
	0xcb, 0x6f, 0xac, 0x45, 0x31, 0x3e, 0x1f, 0x86, 0x81, 0x5e, 0xba, 0x9c, 0x39, 0x3e, 0x54, 0xf3,
	0xf1, 0xdb, 0xab, 0xcc, 0xaa, 0x8a, 0xbc, 0xbb, 0xc6, 0x67, 0xda, 0xf2, 0xa4, 0x99, 0xb6, 0xf9,
	0x6d, 0x12, 0x64, 0xaa, 0x3e, 0xb6, 0x09, 0x2b, 0x5b, 0x96, 0xd7, 0x77, 0x59, 0x64, 0x5e, 0x25,
	0xfe, 0xc5, 0xbc, 0xfa, 0x02, 0x64, 0x2d, 0x21, 0x6b, 0x22, 0x89, 0xab, 0xe9, 0xf7, 0x48, 0x94,
	0xf9, 0x02, 0xf2, 0x0f, 0x54, 0x33, 0x32, 0x43, 0x05, 0xf9, 0x75, 0x8f, 0x2c, 0x46, 0x4e, 0xb1,
	0xaa, 0x90, 0x30, 0xae, 0x3e, 0x7d, 0xc4, 0x75, 0x3f, 0x8e, 0x4e, 0xb8, 0xee, 0x25, 0x49, 0x94,
	0xa1, 0x2a, 0x9e, 0xfc, 0x09, 0x58, 0xba, 0x70, 0x83, 0x2b, 0xdd, 0xe4, 0xe8, 0xf3, 0x64, 0x02,
	0x3c, 0x2e, 0x7c, 0xbd, 0x17, 0xb9, 0xd7, 0xa5, 0xf2, 0xf3, 0x04, 0x3f, 0x19, 0xfc, 0x9a, 0xe1,
	0xdd, 0xe9, 0xf0, 0x18, 0xd5, 0x66, 0xc5, 0x1c, 0xbe, 0xe4, 0xb2, 0xab, 0xa9, 0xf1, 0x31, 0x96,
	0xfa, 0xc3, 0x1b, 0x7d, 0xab, 0x43, 0xd8, 0x71, 0xff, 0xb0, 0x68, 0x79, 0x8e, 0xfa, 0xb6, 0x54,
	0x3f, 0x0f, 0xa8, 0x7d, 0xa2, 0xbe, 0x68, 0xb9, 0x08, 0xe5, 0x47, 0x4b, 0x66, 0x97, 0x65, 0xf2,
	0xee, 0x06, 0xef, 0x86, 0x5b, 0xb1, 0x6e, 0xb8, 0xd0, 0x03, 0xf7, 0x5e, 0x26, 0x00, 0x18, 0x4d,
	0x70, 0x78, 0x13, 0xac, 0xee, 0x19, 0xe5, 0x96, 0x61, 0xb6, 0xda, 0xe5, 0xb6, 0x61, 0x1e, 0xec,
	0xb7, 0x1a, 0x46, 0xb5, 0xfe, 0x41, 0xdd, 0xa8, 0xe5, 0xa6, 0xe0, 0x2a, 0x58, 0x8a, 0x82, 0x0d,
	0x63, 0xbf, 0x56, 0xdf, 0xff, 0x30, 0x97, 0x80, 0x2b, 0x00, 0x46, 0x81, 0x72, 0xb5, 0x5d, 0xff,
	0xdc, 0xc8, 0x4d, 0xc7, 0xe3, 0xd5, 0xbd, 0x4f, 0x5b, 0x46, 0x2d, 0x37, 0x03, 0x35, 0xb0, 0x1c,
	0x8d, 0x37, 0x8d, 0x8f, 0x8d, 0x6a, 0xdb, 0xa8, 0xe5, 0x92, 0xf1, 0x2d, 0x8c, 0x27, 0x8d, 0x7a,
	0xd3, 0xa8, 0xe5, 0x66, 0xf3, 0xc9, 0x6f, 0xbe, 0x2f, 0x4c, 0x55, 0x0e, 0x5e, 0xbd, 0x2d, 0x24,
	0x5e, 0xbf, 0x2d, 0x24, 0x7e, 0x7f, 0x5b, 0x48, 0xbc, 0x78, 0x57, 0x98, 0x7a, 0xfd, 0xae, 0x30,
	0xf5, 0xdb, 0xbb, 0xc2, 0xd4, 0xd3, 0xff, 0x47, 0xaa, 0xe4, 0x20, 0x97, 0x1c, 0x61, 0xca, 0x1e,
	0xb8, 0x98, 0x9d, 0x79, 0xfe, 0xc9, 0x28, 0x20, 0x66, 0xa3, 0x5f, 0x3a, 0x1f, 0x16, 0x43, 0x94,
	0xef, 0x70, 0x4e, 0x8c, 0x99, 0x87, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xaa, 0x84, 0xd8,
	0x36, 0x0c, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxLeasesPerTenant != that1.MaxLeasesPerTenant {
		return false
	}
	if len(this.AllowedList) != len(that1.AllowedList) {
		return false
	}
	for i := range this.AllowedList {
		if this.AllowedList[i] != that1.AllowedList[i] {
			return false
		}
	}
	if this.MaxItemsPerLease != that1.MaxItemsPerLease {
		return false
	}
	if this.MinLeaseDuration != that1.MinLeaseDuration {
		return false
	}
	if this.MaxPendingLeasesPerTenant != that1.MaxPendingLeasesPerTenant {
		return false
	}
	if this.PendingTimeout != that1.PendingTimeout {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PendingTimeout != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PendingTimeout))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxPendingLeasesPerTenant != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxPendingLeasesPerTenant))
		i--
		dAtA[i] = 0x38
	}
	if m.MinLeaseDuration != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MinLeaseDuration))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxItemsPerLease != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxItemsPerLease))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AllowedList) > 0 {
		for iNdEx := len(m.AllowedList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedList[iNdEx])
			copy(dAtA[i:], m.AllowedList[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.AllowedList[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.MaxLeasesPerTenant != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxLeasesPerTenant))
		i--
		dAtA[i] = 0x18
	}
	return len(dAtA) - i, nil
}

func (m *LeaseItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LeaseItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeaseItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.LockedPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Quantity != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SkuUuid) > 0 {
		i -= len(m.SkuUuid)
		copy(dAtA[i:], m.SkuUuid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SkuUuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Lease) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Lease) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Lease) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinLeaseDurationAtCreation != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MinLeaseDurationAtCreation))
		i--
		dAtA[i] = 0x78
	}
	if len(m.MetaHash) > 0 {
		i -= len(m.MetaHash)
		copy(dAtA[i:], m.MetaHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MetaHash)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.ClosureReason) > 0 {
		i -= len(m.ClosureReason)
		copy(dAtA[i:], m.ClosureReason)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ClosureReason)))
		i--
		dAtA[i] = 0x6a
	}
	if m.ExpiredAt != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ExpiredAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExpiredAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintTypes(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x62
	}
	if len(m.RejectionReason) > 0 {
		i -= len(m.RejectionReason)
		copy(dAtA[i:], m.RejectionReason)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RejectionReason)))
		i--
		dAtA[i] = 0x5a
	}
	if m.RejectedAt != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.RejectedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RejectedAt):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintTypes(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x52
	}
	if m.AcknowledgedAt != nil {
		n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.AcknowledgedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.AcknowledgedAt):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintTypes(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x4a
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastSettledAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastSettledAt):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintTypes(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x42
	if m.ClosedAt != nil {
		n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ClosedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ClosedAt):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintTypes(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x3a
	}
	n7, err7 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintTypes(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x32
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ProviderUuid) > 0 {
		i -= len(m.ProviderUuid)
		copy(dAtA[i:], m.ProviderUuid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProviderUuid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreditAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreditAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreditAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReservedAmounts) > 0 {
		for iNdEx := len(m.ReservedAmounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReservedAmounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.PendingLeaseCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PendingLeaseCount))
		i--
		dAtA[i] = 0x20
	}
	if m.ActiveLeaseCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ActiveLeaseCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CreditAddress) > 0 {
		i -= len(m.CreditAddress)
		copy(dAtA[i:], m.CreditAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreditAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxLeasesPerTenant != 0 {
		n += 1 + sovTypes(uint64(m.MaxLeasesPerTenant))
	}
	if len(m.AllowedList) > 0 {
		for _, s := range m.AllowedList {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.MaxItemsPerLease != 0 {
		n += 1 + sovTypes(uint64(m.MaxItemsPerLease))
	}
	if m.MinLeaseDuration != 0 {
		n += 1 + sovTypes(uint64(m.MinLeaseDuration))
	}
	if m.MaxPendingLeasesPerTenant != 0 {
		n += 1 + sovTypes(uint64(m.MaxPendingLeasesPerTenant))
	}
	if m.PendingTimeout != 0 {
		n += 1 + sovTypes(uint64(m.PendingTimeout))
	}
	return n
}

func (m *LeaseItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SkuUuid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Quantity != 0 {
		n += 1 + sovTypes(uint64(m.Quantity))
	}
	l = m.LockedPrice.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Lease) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ProviderUuid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovTypes(uint64(l))
	if m.ClosedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ClosedAt)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastSettledAt)
	n += 1 + l + sovTypes(uint64(l))
	if m.AcknowledgedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.AcknowledgedAt)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RejectedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RejectedAt)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RejectionReason)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ExpiredAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExpiredAt)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ClosureReason)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.MetaHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.MinLeaseDurationAtCreation != 0 {
		n += 1 + sovTypes(uint64(m.MinLeaseDurationAtCreation))
	}
	return n
}

func (m *CreditAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreditAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ActiveLeaseCount != 0 {
		n += 1 + sovTypes(uint64(m.ActiveLeaseCount))
	}
	if m.PendingLeaseCount != 0 {
		n += 1 + sovTypes(uint64(m.PendingLeaseCount))
	}
	if len(m.ReservedAmounts) > 0 {
		for _, e := range m.ReservedAmounts {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLeasesPerTenant", wireType)
			}
			m.MaxLeasesPerTenant = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLeasesPerTenant |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedList = append(m.AllowedList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxItemsPerLease", wireType)
			}
			m.MaxItemsPerLease = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxItemsPerLease |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLeaseDuration", wireType)
			}
			m.MinLeaseDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLeaseDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingLeasesPerTenant", wireType)
			}
			m.MaxPendingLeasesPerTenant = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingLeasesPerTenant |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingTimeout", wireType)
			}
			m.PendingTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LeaseItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LeaseItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LeaseItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkuUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SkuUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LockedPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Lease) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Lease: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Lease: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, LeaseItem{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= LeaseState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClosedAt == nil {
				m.ClosedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ClosedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSettledAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastSettledAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcknowledgedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AcknowledgedAt == nil {
				m.AcknowledgedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.AcknowledgedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RejectedAt == nil {
				m.RejectedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.RejectedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectionReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RejectionReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiredAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiredAt == nil {
				m.ExpiredAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ExpiredAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosureReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClosureReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaHash = append(m.MetaHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MetaHash == nil {
				m.MetaHash = []byte{}
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLeaseDurationAtCreation", wireType)
			}
			m.MinLeaseDurationAtCreation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLeaseDurationAtCreation |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreditAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreditAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreditAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreditAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveLeaseCount", wireType)
			}
			m.ActiveLeaseCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveLeaseCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingLeaseCount", wireType)
			}
			m.PendingLeaseCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingLeaseCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedAmounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReservedAmounts = append(m.ReservedAmounts, types.Coin{})
			if err := m.ReservedAmounts[len(m.ReservedAmounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
