version: "2"

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 15m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - revive
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam

  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - goconst
      - path: '^(app/sim_test\.go|x/(billing|manifest|sku)/simulation/)'
        text: 'G404:'
        linters:
          - gosec

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      custom-order: true
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - blank # blank imports
        - dot # dot imports
        - prefix(github.com/cometbft/cometbft)
        - prefix(github.com/cosmos)
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/strangelove-ventures/poa)
        - prefix(github.com/strangelove-ventures/tokenfactory)
        - prefix(github.com/CosmWasm/wasmd)
        - prefix(github.com/CosmWasm/wasmvm)
        - prefix(github.com/manifest-network/manifest-ledger)

issues:
  max-issues-per-linter: 0
