---
project_name: manifest-ledger

release:
  github:
    owner: manifest-network
    name: manifest-ledger

builds:
  - id: manifest-ledger
    main: ./cmd/manifestd
    binary: manifestd
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=netgo ledger
      - -trimpath
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/cosmos/cosmos-sdk/version.Name=manifest -X github.com/cosmos/cosmos-sdk/version.AppName=manifestd -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger -X github.com/manifest-network/manifest-ledger/app.Bech32Prefix=manifest
    env:
      - CGO_ENABLED=1
    goos:
      - linux
#      - darwin
    goarch:
      - amd64
#      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

snapshot:
  name_template: '{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

git:
  tag_sort: -version:refname

github_urls:
  download: https://github.com/manifest-network/manifest-ledger/releases
