// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: liftedinit/sku/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Unit defines the billing unit for a SKU.
type Unit int32

const (
	// UNIT_UNSPECIFIED is the default unspecified unit.
	Unit_UNIT_UNSPECIFIED Unit = 0
	// UNIT_PER_HOUR is a per-hour billing unit.
	Unit_UNIT_PER_HOUR Unit = 1
	// UNIT_PER_DAY is a per-day billing unit.
	Unit_UNIT_PER_DAY Unit = 2
	// UNIT_PER_MONTH is a per-month billing unit.
	Unit_UNIT_PER_MONTH Unit = 3
	// UNIT_PER_UNIT is a per-unit billing unit.
	Unit_UNIT_PER_UNIT Unit = 4
)

var Unit_name = map[int32]string{
	0: "UNIT_UNSPECIFIED",
	1: "UNIT_PER_HOUR",
	2: "UNIT_PER_DAY",
	3: "UNIT_PER_MONTH",
	4: "UNIT_PER_UNIT",
}

var Unit_value = map[string]int32{
	"UNIT_UNSPECIFIED": 0,
	"UNIT_PER_HOUR":    1,
	"UNIT_PER_DAY":     2,
	"UNIT_PER_MONTH":   3,
	"UNIT_PER_UNIT":    4,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}

func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c58681cc8b08534, []int{0}
}

// Params defines the parameters for the sku module.
type Params struct {
	// allowed_list is the list of addresses allowed to manage SKUs
	// in addition to the module authority.
	AllowedList []string `protobuf:"bytes,1,rep,name=allowed_list,json=allowedList,proto3" json:"allowed_list,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c58681cc8b08534, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAllowedList() []string {
	if m != nil {
		return m.AllowedList
	}
	return nil
}

// SKU defines a stock keeping unit for on-chain billing.
type SKU struct {
	// id is the unique identifier for the SKU.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	// provider is the identifier of the SKU provider.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// name is the human-readable name of the SKU.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// unit is the billing unit for the SKU.
	Unit Unit `protobuf:"varint,4,opt,name=unit,proto3,enum=liftedinit.sku.v1.Unit" json:"unit,omitempty"`
	// base_price is the base price for the SKU.
	BasePrice github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=base_price,json=basePrice,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"base_price"`
	// meta_hash is a hash of the off-chain metadata.
	MetaHash []byte `protobuf:"bytes,6,opt,name=meta_hash,json=metaHash,proto3" json:"meta_hash,omitempty"`
	// active indicates whether the SKU is active.
	Active bool `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *SKU) Reset()         { *m = SKU{} }
func (m *SKU) String() string { return proto.CompactTextString(m) }
func (*SKU) ProtoMessage()    {}
func (*SKU) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c58681cc8b08534, []int{1}
}
func (m *SKU) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SKU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SKU.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SKU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SKU.Merge(m, src)
}
func (m *SKU) XXX_Size() int {
	return m.Size()
}
func (m *SKU) XXX_DiscardUnknown() {
	xxx_messageInfo_SKU.DiscardUnknown(m)
}

var xxx_messageInfo_SKU proto.InternalMessageInfo

func (m *SKU) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SKU) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *SKU) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SKU) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_UNIT_UNSPECIFIED
}

func (m *SKU) GetBasePrice() github_com_cosmos_cosmos_sdk_types.Coin {
	if m != nil {
		return m.BasePrice
	}
	return github_com_cosmos_cosmos_sdk_types.Coin{}
}

func (m *SKU) GetMetaHash() []byte {
	if m != nil {
		return m.MetaHash
	}
	return nil
}

func (m *SKU) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterEnum("liftedinit.sku.v1.Unit", Unit_name, Unit_value)
	proto.RegisterType((*Params)(nil), "liftedinit.sku.v1.Params")
	proto.RegisterType((*SKU)(nil), "liftedinit.sku.v1.SKU")
}

func init() { proto.RegisterFile("liftedinit/sku/v1/types.proto", fileDescriptor_1c58681cc8b08534) }

var fileDescriptor_1c58681cc8b08534 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x89, 0x09, 0xcd, 0xb5, 0x54, 0xee, 0xb5, 0xa2, 0x6e, 0x10, 0x8e, 0xd5, 0xa5,
	0x56, 0x68, 0x6d, 0xa5, 0x0c, 0x48, 0x65, 0x6a, 0xda, 0xa2, 0x56, 0x85, 0x36, 0x38, 0xf5, 0x00,
	0x8b, 0x75, 0xb1, 0xaf, 0xce, 0x29, 0xb6, 0x2f, 0xf2, 0x5d, 0x52, 0xba, 0xf0, 0x07, 0x30, 0x31,
	0x33, 0x31, 0x32, 0x76, 0xe0, 0x8f, 0xe8, 0x58, 0x21, 0x21, 0x31, 0x45, 0x28, 0x19, 0x82, 0xf8,
	0x13, 0x98, 0x90, 0x7f, 0x28, 0x2d, 0x62, 0xb1, 0xdf, 0xfb, 0x7e, 0xdf, 0x3d, 0xfb, 0x7d, 0xde,
	0xc1, 0xc7, 0x01, 0x3d, 0x17, 0xc4, 0xa3, 0x11, 0x15, 0x26, 0xef, 0x0d, 0xcc, 0x61, 0xc3, 0x14,
	0x97, 0x7d, 0xc2, 0x8d, 0x7e, 0xcc, 0x04, 0x43, 0x4b, 0xb7, 0xb6, 0xc1, 0x7b, 0x03, 0x63, 0xd8,
	0xa8, 0x2e, 0xe1, 0x90, 0x46, 0xcc, 0x4c, 0x9f, 0x59, 0x55, 0x55, 0x75, 0x19, 0x0f, 0x19, 0x37,
	0x3b, 0x98, 0x13, 0x73, 0xd8, 0xe8, 0x10, 0x81, 0x1b, 0xa6, 0xcb, 0x68, 0x94, 0xfb, 0x6b, 0x99,
	0xef, 0xa4, 0x99, 0x99, 0x25, 0xb9, 0xb5, 0xe2, 0x33, 0x9f, 0x65, 0x7a, 0x12, 0x65, 0xea, 0x3a,
	0x86, 0xe5, 0x16, 0x8e, 0x71, 0xc8, 0xd1, 0x73, 0xb8, 0x80, 0x83, 0x80, 0x5d, 0x10, 0xcf, 0x09,
	0x28, 0x17, 0x0a, 0xd0, 0x4a, 0x7a, 0xa5, 0xa9, 0x7c, 0xfb, 0xba, 0xb5, 0x92, 0xf7, 0xd9, 0xf5,
	0xbc, 0x98, 0x70, 0xde, 0x16, 0x31, 0x8d, 0x7c, 0x6b, 0x3e, 0xaf, 0x7e, 0x49, 0xb9, 0xd8, 0xa9,
	0xfe, 0xfa, 0x5c, 0x03, 0x1f, 0xa6, 0x57, 0xf5, 0x7c, 0x8c, 0x74, 0xc2, 0xac, 0xf1, 0xfa, 0xf7,
	0x22, 0x2c, 0xb5, 0x8f, 0x6d, 0xb4, 0x01, 0x8b, 0xd4, 0x53, 0x80, 0x06, 0x74, 0xa9, 0xb9, 0xfa,
	0x7b, 0x54, 0x5b, 0xa6, 0xde, 0x26, 0x0b, 0xa9, 0x20, 0x61, 0x5f, 0x5c, 0x6e, 0xf2, 0xac, 0x6b,
	0x91, 0x7a, 0xa8, 0x0a, 0xe7, 0xfa, 0x31, 0x1b, 0x52, 0x8f, 0xc4, 0x4a, 0x51, 0x03, 0x7a, 0xc5,
	0x9a, 0xe5, 0x08, 0x41, 0x29, 0xc2, 0x21, 0x51, 0x4a, 0xa9, 0x9e, 0xc6, 0xe8, 0x09, 0x94, 0x06,
	0x11, 0x15, 0x8a, 0xa4, 0x01, 0x7d, 0x71, 0x7b, 0xd5, 0xf8, 0x8f, 0xa4, 0x61, 0x47, 0x54, 0x58,
	0x69, 0x11, 0x7a, 0x0f, 0x61, 0x02, 0xcf, 0xe9, 0xc7, 0xd4, 0x25, 0xca, 0x3d, 0x0d, 0xe8, 0xf3,
	0xdb, 0x6b, 0x46, 0x3e, 0x61, 0xe2, 0x18, 0x39, 0x56, 0x63, 0x8f, 0xd1, 0xa8, 0xb9, 0x7f, 0x3d,
	0xaa, 0x15, 0xfe, 0x8c, 0x6a, 0x1b, 0x3e, 0x15, 0xdd, 0x41, 0xc7, 0x70, 0x59, 0x98, 0x63, 0xcd,
	0x5f, 0x5b, 0xdc, 0xeb, 0xe5, 0x8b, 0x4c, 0x0e, 0x7c, 0x9a, 0x5e, 0xd5, 0xe7, 0x03, 0xe2, 0x63,
	0xf7, 0xd2, 0x49, 0xf6, 0xf2, 0x65, 0x7a, 0x55, 0x07, 0x56, 0x25, 0x69, 0xdc, 0x4a, 0xbe, 0x88,
	0x1e, 0xc1, 0x4a, 0x48, 0x04, 0x76, 0xba, 0x98, 0x77, 0x95, 0xb2, 0x06, 0xf4, 0x05, 0x6b, 0x2e,
	0x11, 0x0e, 0x31, 0xef, 0xa2, 0x87, 0xb0, 0x8c, 0x5d, 0x41, 0x87, 0x44, 0xb9, 0xaf, 0x01, 0x7d,
	0xce, 0xca, 0xb3, 0x9d, 0xe5, 0x04, 0xed, 0xe2, 0x1d, 0xb4, 0xed, 0x63, 0xbb, 0xde, 0x85, 0x52,
	0x32, 0x17, 0x5a, 0x81, 0xb2, 0x7d, 0x72, 0x74, 0xe6, 0xd8, 0x27, 0xed, 0xd6, 0xc1, 0xde, 0xd1,
	0x8b, 0xa3, 0x83, 0x7d, 0xb9, 0x80, 0x96, 0xe0, 0x83, 0x54, 0x6d, 0x1d, 0x58, 0xce, 0xe1, 0xa9,
	0x6d, 0xc9, 0x00, 0xc9, 0x70, 0x61, 0x26, 0xed, 0xef, 0xbe, 0x91, 0x8b, 0x08, 0xc1, 0xc5, 0x99,
	0xf2, 0xea, 0xf4, 0xe4, 0xec, 0x50, 0x2e, 0xfd, 0x73, 0x30, 0x09, 0x64, 0xa9, 0xf9, 0xfa, 0x7a,
	0xac, 0x82, 0x9b, 0xb1, 0x0a, 0x7e, 0x8e, 0x55, 0xf0, 0x71, 0xa2, 0x16, 0x6e, 0x26, 0x6a, 0xe1,
	0xc7, 0x44, 0x2d, 0xbc, 0x7d, 0x76, 0x07, 0x4b, 0x88, 0x23, 0x7a, 0x4e, 0xb8, 0xd8, 0x8a, 0x88,
	0xb8, 0x60, 0x71, 0xef, 0x56, 0x08, 0x88, 0xe7, 0x93, 0xd8, 0x7c, 0x97, 0xfe, 0x7a, 0xca, 0xaa,
	0x53, 0x4e, 0xaf, 0xdf, 0xd3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x93, 0x0b, 0x7d, 0x16,
	0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AllowedList) != len(that1.AllowedList) {
		return false
	}
	for i := range this.AllowedList {
		if this.AllowedList[i] != that1.AllowedList[i] {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedList) > 0 {
		for iNdEx := len(m.AllowedList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedList[iNdEx])
			copy(dAtA[i:], m.AllowedList[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.AllowedList[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SKU) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SKU) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SKU) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.MetaHash) > 0 {
		i -= len(m.MetaHash)
		copy(dAtA[i:], m.MetaHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MetaHash)))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.BasePrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Unit != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Unit))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AllowedList) > 0 {
		for _, s := range m.AllowedList {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *SKU) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Unit != 0 {
		n += 1 + sovTypes(uint64(m.Unit))
	}
	l = m.BasePrice.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.MetaHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Active {
		n += 2
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedList = append(m.AllowedList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SKU) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SKU: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SKU: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unit", wireType)
			}
			m.Unit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Unit |= Unit(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasePrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BasePrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaHash = append(m.MetaHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MetaHash == nil {
				m.MetaHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
