// Command docs-reference renders the registered billing/SKU protobuf and CLI
// surfaces. Runtime policy belongs in the linked hand-written module guides.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"

	servercmd "github.com/cosmos/cosmos-sdk/server/cmd"

	"github.com/manifest-network/manifest-ledger/app"
	ledgercmd "github.com/manifest-network/manifest-ledger/cmd/manifestd/cmd"
)

const (
	defaultOutput = "docs/reference/BILLING_SKU.md"
	queryCategory = "query"
	txCategory    = "tx"
)

type moduleSpec struct{ name, namespace string }

var modules = []moduleSpec{
	{name: "billing", namespace: "liftedinit.billing.v1"},
	{name: "sku", namespace: "liftedinit.sku.v1"},
}

func main() {
	output := flag.String("output", defaultOutput, "reference path relative to the current directory")
	check := flag.Bool("check", false, "fail if the checked-in reference differs; do not rewrite it")
	flag.Parse()
	if err := run(*output, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(output string, check bool) error {
	// NewRootCmd reads client.toml while configuring AutoCLI. Isolate that read
	// so the reference cannot depend on an operator's real node configuration.
	home, err := os.MkdirTemp("", "manifest-docs-reference-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(home) }()
	previousHome := app.DefaultNodeHome
	app.DefaultNodeHome = home
	defer func() { app.DefaultNodeHome = previousHome }()
	root := ledgercmd.NewRootCmd()
	// The production launcher adds inherited home/trace/logging flags outside
	// NewRootCmd. Its help path installs them without running any query, tx, or
	// pre-run configuration hooks; don't duplicate those flag definitions here.
	root.SetArgs([]string{"--help"})
	root.SetOut(io.Discard)
	root.SetErr(io.Discard)
	if err := servercmd.Execute(root, "MANIFESTD", home); err != nil {
		return err
	}
	content, err := render(root, protoregistry.GlobalFiles, modules, home)
	if err != nil {
		return err
	}
	if check {
		existing, err := os.ReadFile(output) //nolint:gosec // -output is an explicit local destination, not network input.
		if err != nil {
			return err
		}
		if !bytes.Equal(existing, content) {
			return errors.New("generated billing/SKU reference is stale; run make docs-reference")
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil { //nolint:gosec // Generated reference directories contain public documentation.
		return err
	}
	return os.WriteFile(output, content, 0o644) //nolint:gosec // Generated reference is public documentation, readable like other checked-in Markdown.
}

type descriptorResolver interface {
	FindDescriptorByName(protoreflect.FullName) (protoreflect.Descriptor, error)
}

func render(root *cobra.Command, resolver descriptorResolver, specs []moduleSpec, home string) ([]byte, error) {
	var out strings.Builder
	out.WriteString("# Billing and SKU generated reference\n\n")
	out.WriteString("Generated by `make docs-reference` from registered protobuf descriptors and the real `manifestd` command tree. Check with `make docs-reference-check`; edit the source definitions, not this file.\n\n")
	out.WriteString("This reference lists structural fields, methods, commands, and flags. Protobuf singular fields can still be required by runtime validation. Monetary units, authorization, pagination limits, lifecycle rules, and metadata preserve/clear semantics are defined in the [billing API](../../x/billing/docs/API.md) and [SKU API](../../x/sku/docs/API.md). CLI defaults below assume an empty client configuration; node-home paths are shown as `~/.manifest`.\n\n")
	out.WriteString("Flag requirements reflect Cobra's required-flag annotations; handlers may impose additional requirements. Hidden compatibility flags are listed and marked; their presence does not imply the handler accepts every value or mode.\n\n")
	for _, spec := range specs {
		fmt.Fprintf(&out, "- [%s RPCs](#%s-rpcs) · [query commands](#%s-query-commands) · [transaction commands](#%s-tx-commands)\n", spec.name, spec.name, spec.name, spec.name)
	}
	out.WriteString("- [Message fields and enums](#message-fields-and-enums)\n\n")
	messages := make(map[protoreflect.FullName]protoreflect.MessageDescriptor)
	enums := make(map[protoreflect.FullName]protoreflect.EnumDescriptor)
	for _, spec := range specs {
		fmt.Fprintf(&out, "## %s RPCs\n\n| RPC path | Request | Response |\n|---|---|---|\n", spec.name)
		for _, serviceName := range []string{"Query", "Msg"} {
			name := protoreflect.FullName(spec.namespace + "." + serviceName)
			descriptor, err := resolver.FindDescriptorByName(name)
			if err != nil {
				return nil, fmt.Errorf("resolve service %s: %w", name, err)
			}
			service, ok := descriptor.(protoreflect.ServiceDescriptor)
			if !ok {
				return nil, fmt.Errorf("%s is not a service", name)
			}
			for i := 0; i < service.Methods().Len(); i++ {
				method := service.Methods().Get(i)
				request, response := typeLink(method.Input()), typeLink(method.Output())
				if method.IsStreamingClient() {
					request += " (stream)"
				}
				if method.IsStreamingServer() {
					response += " (stream)"
				}
				fmt.Fprintf(&out, "| `%s/%s` | %s | %s |\n", name, method.Name(), request, response)
				collectMessage(method.Input(), messages, enums)
				collectMessage(method.Output(), messages, enums)
			}
		}
		out.WriteString("\n")
		for _, category := range []string{queryCategory, txCategory} {
			command, remaining, err := root.Find([]string{category, spec.name})
			if err != nil || len(remaining) != 0 || command.Name() != spec.name {
				return nil, fmt.Errorf("module command %s %s missing from manifestd", category, spec.name)
			}
			if err := renderCommands(&out, command, spec.name, category, home); err != nil {
				return nil, err
			}
		}
	}
	out.WriteString("## Message fields and enums\n\n")
	for _, name := range sortedNames(messages) {
		message := messages[name]
		fmt.Fprintf(&out, "<a id=\"%s\"></a>\n\n### `%s`\n\n", typeAnchor(message), name)
		if message.Fields().Len() == 0 {
			out.WriteString("No fields.\n\n")
			continue
		}
		out.WriteString("| Field | Number | Protobuf type | Shape |\n|---|---|---|---|\n")
		for i := 0; i < message.Fields().Len(); i++ {
			field := message.Fields().Get(i)
			shape := "singular"
			if field.IsMap() {
				shape = "map"
			} else if field.IsList() {
				shape = "repeated"
			} else if oneof := field.ContainingOneof(); oneof != nil && !oneof.IsSynthetic() {
				shape = "oneof " + string(oneof.Name())
			} else if field.HasOptionalKeyword() {
				shape = "optional"
			}
			fmt.Fprintf(&out, "| `%s` | %d | %s | %s |\n", field.Name(), field.Number(), fieldType(field), escape(shape))
		}
		out.WriteString("\n")
	}
	for _, name := range sortedNames(enums) {
		enum := enums[name]
		fmt.Fprintf(&out, "<a id=\"%s\"></a>\n\n### `%s`\n\n| Name | Number |\n|---|---|\n", typeAnchor(enum), name)
		for i := 0; i < enum.Values().Len(); i++ {
			value := enum.Values().Get(i)
			fmt.Fprintf(&out, "| `%s` | %d |\n", value.Name(), value.Number())
		}
		out.WriteString("\n")
	}
	return []byte(strings.TrimRight(out.String(), "\n") + "\n"), nil
}

func collectMessage(message protoreflect.MessageDescriptor, messages map[protoreflect.FullName]protoreflect.MessageDescriptor, enums map[protoreflect.FullName]protoreflect.EnumDescriptor) {
	if _, seen := messages[message.FullName()]; seen {
		return
	}
	messages[message.FullName()] = message
	for i := 0; i < message.Fields().Len(); i++ {
		field := message.Fields().Get(i)
		if field.IsMap() {
			field = field.MapValue()
		}
		if nested := field.Message(); nested != nil {
			collectMessage(nested, messages, enums)
		}
		if enum := field.Enum(); enum != nil {
			enums[enum.FullName()] = enum
		}
	}
}

func sortedNames[T any](values map[protoreflect.FullName]T) []protoreflect.FullName {
	names := make([]protoreflect.FullName, 0, len(values))
	for name := range values {
		names = append(names, name)
	}
	slices.Sort(names)
	return names
}

func typeAnchor(descriptor protoreflect.Descriptor) string {
	return "type-" + strings.ToLower(strings.ReplaceAll(string(descriptor.FullName()), ".", "-"))
}

func typeLink(descriptor protoreflect.Descriptor) string {
	return fmt.Sprintf("[`%s`](#%s)", descriptor.FullName(), typeAnchor(descriptor))
}

func fieldType(field protoreflect.FieldDescriptor) string {
	if field.IsMap() {
		return fmt.Sprintf("map&lt;%s, %s&gt;", fieldType(field.MapKey()), fieldType(field.MapValue()))
	}
	if message := field.Message(); message != nil {
		return typeLink(message)
	}
	if enum := field.Enum(); enum != nil {
		return typeLink(enum)
	}
	return "`" + field.Kind().String() + "`"
}

type flagDoc struct {
	name, shorthand, kind, defaultValue, usage, required, deprecated string
	hidden                                                           bool
}

type commandDoc struct {
	command *cobra.Command
	flags   map[string]flagDoc
}

func renderCommands(out *strings.Builder, module *cobra.Command, name, category, home string) error {
	var commands []commandDoc
	var walk func(*cobra.Command)
	walk = func(command *cobra.Command) {
		if command.Runnable() && !command.HasSubCommands() {
			command.InitDefaultHelpFlag()
			flags := make(map[string]flagDoc)
			collect := func(flag *pflag.Flag) {
				required := "no"
				if slices.Contains(flag.Annotations[cobra.BashCompOneRequiredFlag], "true") {
					required = "yes"
				}
				flags[flag.Name] = flagDoc{
					name: flag.Name, shorthand: flag.Shorthand, kind: flag.Value.Type(),
					defaultValue: strings.ReplaceAll(flag.DefValue, home, "~/.manifest"),
					usage:        flag.Usage, required: required, deprecated: flag.Deprecated, hidden: flag.Hidden,
				}
			}
			command.InheritedFlags().VisitAll(collect)
			command.NonInheritedFlags().VisitAll(collect)
			commands = append(commands, commandDoc{command: command, flags: flags})
		}
		for _, child := range command.Commands() {
			walk(child)
		}
	}
	walk(module)
	if len(commands) == 0 {
		return fmt.Errorf("module command %s has no runnable subcommands", module.CommandPath())
	}
	slices.SortFunc(commands, func(a, b commandDoc) int { return strings.Compare(a.command.CommandPath(), b.command.CommandPath()) })
	shared := make(map[string]flagDoc)
	for name, flag := range commands[0].flags {
		shared[name] = flag
	}
	for _, command := range commands[1:] {
		for name, flag := range shared {
			if other, ok := command.flags[name]; !ok || other != flag {
				delete(shared, name)
			}
		}
	}
	fmt.Fprintf(out, "## %s %s commands\n\n", name, category)
	out.WriteString("Flags shared by every command in this section:\n\n")
	renderFlags(out, shared)
	for _, item := range commands {
		command := item.command
		fmt.Fprintf(out, "### `%s %s`\n\n%s\n\n", command.Parent().CommandPath(), command.Use, escape(command.Short))
		if len(command.Aliases) > 0 {
			fmt.Fprintf(out, "Aliases: `%s`.\n\n", escape(strings.Join(command.Aliases, "`, `")))
		}
		if command.Hidden || command.Deprecated != "" {
			fmt.Fprintf(out, "Hidden: %t. Deprecated: %s.\n\n", command.Hidden, escape(command.Deprecated))
		}
		specific := make(map[string]flagDoc)
		for name, flag := range item.flags {
			if _, common := shared[name]; !common {
				specific[name] = flag
			}
		}
		if len(specific) > 0 {
			renderFlags(out, specific)
		}
	}
	return nil
}

func renderFlags(out *strings.Builder, flags map[string]flagDoc) {
	if len(flags) == 0 {
		out.WriteString("None.\n\n")
		return
	}
	names := make([]string, 0, len(flags))
	for name := range flags {
		names = append(names, name)
	}
	slices.Sort(names)
	out.WriteString("| Flag | Type | Default | Required | Description |\n|---|---|---|---|---|\n")
	for _, name := range names {
		flag := flags[name]
		usage := flag.usage
		if flag.hidden {
			usage += " (hidden)"
		}
		if flag.deprecated != "" {
			usage += " (deprecated: " + flag.deprecated + ")"
		}
		label := "--" + name
		if flag.shorthand != "" {
			label += ", -" + flag.shorthand
		}
		fmt.Fprintf(out, "| `%s` | `%s` | `%s` | %s | %s |\n", label, flag.kind, escape(fmt.Sprintf("%q", flag.defaultValue)), flag.required, escape(usage))
	}
	out.WriteString("\n")
}

func escape(value string) string {
	return strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "|", "\\|", "\n", "<br>", "\r", "").Replace(value)
}
